[images]
  remote_images = ["*"]

[build]
  command = "echo 'Build completed'"
  publish = "/"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
